name: Greeting Workflow
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a greeting
        run: echo "The CI pipeline has successfully started!"
  test-py-add:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
         
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.11'
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

     - name: Run tests
       run: pytest -v
  build-and-test:
    runs-on: ubuntu-latest
        # --- THIS IS THE MATRIX SECTION ---
    # strategy:
    #   matrix:
    #     node-version: 20.x
    # ----------------------------------
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      # - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install # Even if the folder is empty, this is good practice

      - name: Run Unit Tests
        run: node test

      - name: Run Security Check
        run: node app.js
        env:
          # This connects the GitHub Secret to the code's environment variable
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

  package:
    # This ensures packaging ONLY happens if BOTH Node versions pass
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Build Artifact
        run: zip -r weather-app-dist.zip . -x "*.git*"
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-app-dist
          path: weather-app-dist.zip
